#!/usr/bin/env python3
# SUGGESTION: generated by Claude — review before merging
"""2.3 RESTCONF writes — FIXTURE replay (DevNet box auth-locked 2026-05-28).
Mirrors the 2.2 create->verify->delete cycle in RESTCONF verbs, against
recorded responses. Re-run live when the sandbox authenticates: same URLs,
same payload — swap replay() for the requests calls from 03_restconf_write.py.

FIXTURE HONESTY:
- Status codes (201/204/200/404/409) are RFC 8040 write semantics — confident.
- Error-body shape mirrors THIS box's real 401 output (minimal: error-type +
  error-tag, no error-message) — that format was confirmed live earlier today.
- The exact 404-on-DELETE body is MODELED from RFC, not captured from this box.
  Confirm verbatim against the live device before trusting that one in a mock.
"""
import json

IFACE = "Loopback200"
URL = f"/restconf/data/ietf-interfaces:interfaces/interface={IFACE}"
PAYLOAD = {"ietf-interfaces:interface": {
    "name": IFACE, "description": "ENAUTO 2.3 RESTCONF lab",
    "type": "iana-if-type:softwareLoopback", "enabled": True,
    "ietf-ip:ipv4": {"address": [{"ip": "20.201.201.1",
                                  "netmask": "255.255.255.0"}]}}}
ERR_EXISTS  = {"ietf-restconf:errors": {"error": [{"error-type": "protocol", "error-tag": "data-exists"}]}}
ERR_MISSING = {"ietf-restconf:errors": {"error": [{"error-type": "protocol", "error-tag": "data-missing"}]}}

# (intent, method, body-sent?, status, resp-body, meaning)
CYCLE = [
    ("create (target absent)", "PUT",    True,  201, "",          "201 Created — new resource"),
    ("verify",                 "GET",     False, 200, PAYLOAD,     "200 — present, body returned"),
    ("re-PUT identical data",  "PUT",    True,  204, "",          "204 No Content — replaced; PUT is idempotent"),
    ("POST same target",       "POST",   True,  409, ERR_EXISTS,  "409 Conflict — POST is create-only"),
    ("delete",                 "DELETE", False, 204, "",          "204 No Content — removed"),
    ("verify gone",            "GET",     False, 404, "",          "404 — absent"),
    ("delete again",           "DELETE", False, 404, ERR_MISSING, "404 — NOT idempotent (cf NETCONF remove)"),
]

def replay(step):
    intent, method, sent, status, body, meaning = step
    print(f"\n[{intent}]  {method} {URL}")
    if sent:
        print("  body:", json.dumps(PAYLOAD["ietf-interfaces:interface"], separators=(",", ":")))
    print(f"  -> {status}   {meaning}")
    if body:
        print("  resp:", json.dumps(body, separators=(",", ":")) if isinstance(body, dict) else body)

def main():
    print("=== 2.3 RESTCONF write cycle (FIXTURE replay) ===")
    for step in CYCLE:
        replay(step)
    print("\n--- verb -> intent -> NETCONF analogue ---")
    print("  PUT     create-or-replace          ~ edit-config replace")
    print("  PATCH   merge (not shown here)      ~ edit-config merge")
    print("  POST    create-only, 409 if exists  ~ edit-config create")
    print("  DELETE  delete, 404 if absent       ~ NETCONF delete (NOT remove)")
    print("\nKey: RESTCONF DELETE has no idempotent 'remove' twin — absent target = 404.")

if __name__ == "__main__":
    main()