import functools
import json
import os
import time
from pathlib import Path

from fastmcp import FastMCP

import tools_netconf
import tools_restconf
import tools_netmiko
import tools_acl

mcp = FastMCP(name="enauto-lab")

LOG_PATH = Path(__file__).parent / "tool_calls.log"

# Only a human setting this on the server host unlocks writes. The agent can pass
# apply=True on any tool call it likes — this is the actual gate, and it lives
# outside the agent's reach (blueprint 5.3: bound the agent's blast radius).
ALLOW_APPLY = os.environ.get("ENAUTO_ALLOW_APPLY", "false").lower() == "true"


def log_tool_call(func):
    """Append every call (args, result, timestamp) to tool_calls.log.

    This runs regardless of what gets reported back in chat, so the log is an
    independent record you can diff against — not something to just trust.
    """
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        # SUGGESTION: generated by Claude — review before merging.
        # A bare call here let exceptions skip the log entirely — the one call
        # that fails live is exactly the one the audit trail must not miss.
        result = None
        error = None
        try:
            result = func(*args, **kwargs)
            return result
        except Exception as e:
            error = str(e)
            raise
        finally:
            entry = {
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
                "tool": func.__name__,
                "args": kwargs,
                "result": result if error is None else {"error": error},
            }
            with open(LOG_PATH, "a") as f:
                f.write(json.dumps(entry) + "\n")
    return wrapper


@mcp.tool
@log_tool_call
def mdt_subscription_netconf() -> str:
    """Get MDT subscription 1 from iosxe-01 via NETCONF (ncclient get-config, subtree filter). Returns raw XML."""
    return tools_netconf.get_mdt_subscription()


@mcp.tool
@log_tool_call
def mdt_subscription_restconf() -> dict:
    """Get MDT subscription 1 from iosxe-01 via RESTCONF (GET, yang-data+json). Returns parsed JSON."""
    return tools_restconf.get_mdt_subscription()


@mcp.tool
@log_tool_call
def mdt_subscription_netmiko() -> str:
    """Get MDT subscription 1 from iosxe-01 via Netmiko (show running-config | section telemetry). Returns raw CLI text."""
    return tools_netmiko.get_mdt_subscription()


@mcp.tool
@log_tool_call
def mdt_subscription_set_period(period_cs: int, apply: bool = False) -> str:
    """Change MDT subscription 1's period (centiseconds) on iosxe-01 via NETCONF edit-config.

    dry-run unless apply=True, and apply is refused unless the server host has
    ENAUTO_ALLOW_APPLY=true set — that flag is not something this tool call can set itself.
    """
    if apply and not ALLOW_APPLY:
        return "REFUSED: apply=True requested but ENAUTO_ALLOW_APPLY is not set on the server host."
    return tools_netconf.set_mdt_subscription_period(period_cs, apply=apply)


@mcp.tool
@log_tool_call
def create_automation_acl(apply: bool = False) -> dict:
    """Create standard ACL AUTOMATION_ACL on iosxe-01 via RESTCONF (Cisco-IOS-XE-native model).

    dry-run unless apply=True, and apply is refused unless the server host has
    ENAUTO_ALLOW_APPLY=true set — that flag is not something this tool call can set itself.
    """
    if apply and not ALLOW_APPLY:
        return {"error": "REFUSED: apply=True requested but ENAUTO_ALLOW_APPLY is not set on the server host."}
    return tools_acl.create_automation_acl(apply=apply)


if __name__ == "__main__":
    mcp.run()
