# SUGGESTION: generated by Claude — review before merging.
import os

import requests
from dotenv import load_dotenv
from requests.auth import HTTPBasicAuth
import urllib3

urllib3.disable_warnings()
load_dotenv()

URL = f"https://{os.environ['IOS_XE_HOST']}/restconf/data/Cisco-IOS-XE-mdt-cfg:mdt-config-data/mdt-subscription=1"
HEADERS = {"Accept": "application/yang-data+json"}
AUTH = HTTPBasicAuth(os.environ["IOS_XE_USERNAME"], os.environ["IOS_XE_PASSWORD"])


def get_mdt_subscription() -> dict:
    response = requests.get(URL, headers=HEADERS, auth=AUTH, verify=False)
    response.raise_for_status()
    return response.json()
