# SUGGESTION: generated by Claude — review before merging.
import os

import requests
from dotenv import load_dotenv
from requests.auth import HTTPBasicAuth
import urllib3

urllib3.disable_warnings()
load_dotenv()

URL = f"https://{os.environ['IOS_XE_HOST']}/restconf/data/Cisco-IOS-XE-native:native/ip/access-list/standard"
HEADERS = {
    "Content-Type": "application/yang-data+json",
    "Accept": "application/yang-data+json",
}
AUTH = HTTPBasicAuth(os.environ["IOS_XE_USERNAME"], os.environ["IOS_XE_PASSWORD"])

ACL_NAME = "AUTOMATION_ACL"

# [Certain] — live-verified on iosxe-01 (17.15.04c): PATCH returns 204, and a
# RESTCONF GET on this same path reads back all four entries intact. Took 4 rounds
# of live 400s to land on this shape: (1) wrong module prefix, fixed to
# Cisco-IOS-XE-acl:standard; (2) unknown-element std-ace-rule, fixed to the real list
# access-list-seq-rule; (3) unknown-element host directly under permit — permit/deny
# each `uses ipv4-std-ace-grouping`, which nests a "std-ace" container one level down
# before the source-choice (host/ipv4-prefix/any). Distinct sequence numbers per
# remark/ACE pair (10/11, 20/21) since access-list-seq-rule is keyed by sequence.
PAYLOAD = {
    "Cisco-IOS-XE-acl:standard": [
        {
            "name": ACL_NAME,
            "access-list-seq-rule": [
                {"sequence": 10, "remark": "Automation servers"},
                {"sequence": 11, "permit": {"std-ace": {"host": "10.0.0.1"}}},
                {"sequence": 20, "remark": "Syslog servers"},
                {"sequence": 21, "permit": {"std-ace": {"host": "10.0.1.1"}}},
            ],
        }
    ]
}


def create_automation_acl(apply: bool = False) -> dict:
    if not apply:
        return {"dry_run": True, "method": "PATCH", "url": URL, "payload": PAYLOAD}

    response = requests.patch(URL, json=PAYLOAD, headers=HEADERS, auth=AUTH, verify=False)
    # SUGGESTION: generated by Claude — review before merging.
    # raise_for_status() alone discards the response body, which is where the
    # device names the actual bad leaf — surface it instead of just the status code.
    try:
        response.raise_for_status()
    except requests.HTTPError as e:
        raise RuntimeError(f"{e} — response body: {response.text}") from e
    return {"dry_run": False, "status_code": response.status_code}
