# SUGGESTION: generated by Claude — review before merging.
import os

from dotenv import load_dotenv
from netmiko import ConnectHandler

load_dotenv()

DEVICE = {
    "device_type": "cisco_xe",
    "host": os.environ["IOS_XE_HOST"],
    "username": os.environ["IOS_XE_USERNAME"],
    "password": os.environ["IOS_XE_PASSWORD"],
}


def get_mdt_subscription() -> str:
    with ConnectHandler(**DEVICE) as conn:
        return str(conn.send_command("show running-config | section telemetry ietf subscription 1"))
