---
- name: Get SD-WAN device list
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get all devices from vManage
      cisco.catalystwan.devices_info:
        device_category: vedges
        manager_credentials:
          url: "{{ vmanage_base_url }}"
          username: "{{ vmanage_username }}"
          password: "{{ vmanage_password }}"
      register: devices

    - name: Display devices
      ansible.builtin.debug:
        msg: "{{ item.host_name }} — {{ item.system_ip }} ({{ item.reachability }})"
      loop: "{{ devices.devices }}"